version: "3.9"

services:
  postgres:
    image: postgres
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: asgthunder
      POSTGRES_PASSWORD: asgthunder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../../backend/dbscripts/runtimedb/postgres.sql:/docker-entrypoint-initdb.d/runtime-postgres.sql
      - ../../backend/dbscripts/thunderdb/postgres.sql:/docker-entrypoint-initdb.d/thunder-postgres.sql

volumes:
  postgres_data:
